#!/bin/bash
#
# declare the DNSSRV list array
declare DNSSRV

# Check whether the user had supplied -h or --help.  If yes, then display usage example.
#
	if [[ $1 == "--help" || $1 == "-h" ]]
		then
			echo -e "\nThis script will attempt to resolve NAPTR for Fuze's public GeoDNS domain by using a Public DNS Server in the chosen country.  Enter a 2 letter country code (e.g., uk, de, au, etc.).\nThe command issued is:\ndig @SERVER NAPTR edge.uc.fuze.site +short\n\nUsage: $0 <2 Letter Country Abbreviation>."
			echo -e "\nThis script references https://public-dns.info/#countries and the lists of DNS servers found on pages like https://public-dns.info/nameserver/gb.txt for example.  The script uses the country code provided to find the first IP address from such a list on the public-dns.info website." 
			exit 1
	fi
#
# If there were no arguments provided, and they didn't ask for help, prompt for the input and continue.
#
	if [ $# -lt 1 ]
		then
			echo -e -n "\nEnter a 2 Letter Country Abbreviation (e.g., gb, de, au):  "
			read -r CC
		else
			CC=$1
	fi
#
# Look up DNS Servers for the Country Code
#
# First, just make sure the CC value is changed to lower case, and set the value to lcc
#
lcc=`echo $CC | tr '[:upper:]' '[:lower:]'`

#
# get the list of files from the URL below.  set the array (majick), then delete the file

curl -s https://public-dns.info/nameserver/$lcc.txt > ./dnssrv_list.txt

IFS=$'\n' read -d '' -r -a DNSSRV < ./dnssrv_list.txt

rm ./dnssrv_list.txt

SRVTOT=${#DNSSRV[@]}
#
# How many servers are in the array?
echo -e "According to https://public-dns.info there are $SRVTOT DNS servers in $lcc at this time!\n"

if [ $SRVTOT -lt 20 ] ; then
#
# Found this method to print the array nicely into columns.  The "tab stop" in the printf notation helps.
	echo "Here's the whole list:"
	for value in "${DNSSRV[@]}"; do 
    		printf "%-8s\n" "${value}"
	done | column
else
	echo "Printing the first 20 from the list, but there are :"
	for k in {0..19}; do
    		printf "%-8s\n" "${DNSSRV[$k]}"
	done | column
fi

echo 

# Ask how many to poll?
((snum=$SRVTOT+1))
while [ $snum -gt $SRVTOT ]; do
	echo -e -n "How many of the $SRVTOT servers in $lcc should be tested?  " 
	read -r newnum
	snum=$newnum
done
#
# Since the array is "0 based" subract 1 from snum, and then make sure all the loops start with "0" too
#
((snum=$snum-1))

for i in $(seq 0 $snum)
	do
		echo -e "\t${DNSSRV[$i]}"
	done
#
# Lookup the Fuze Domain from the DNS Server in that Country

for j in $(seq 0 $snum)
	do
		echo -e "*** Now Testing ${DNSSRV[$j]} ***"
       		echo -e "dig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3 | sort\n"
       		dig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3 | sort
		echo 
	done
