#!/bin/bash
#
# declare the DNSSRV list array

declare DNSSRV
declare ANSWER

# Check whether the user had supplied -h or --help.  If yes, then display usage example.
#
	if [[ $1 == "--help" || $1 == "-h" ]]
		then
			echo -e "\nUsage: $0 <2 Letter Country Abbreviation>"
			echo -e "\nThis script will attempt to resolve NAPTR for Fuze's public GeoDNS domain by using a Public DNS Server in the chosen country.  "
			echo -e "Enter a 2 letter country code (e.g., gb, de, au, etc.).  If at least 1 result for a Public DNS Server is found, then the command issued is:"
			echo -e "\n\tdig @SERVER NAPTR edge.uc.fuze.site +short +timeout=3"
			echo -e "\nThis script references Public DNS Server information from:\thttps://public-dns.info/#countries"
			echo -e "\nThe script uses the country code provided to find the IP addresses of public DNS servers in that country from the corresponding list found at the https://public-dns.info website.\n" 
			exit 1
	fi
#
# If there were no arguments provided, and they didn't ask for help, prompt for the input and continue.
#
((SRVTOT=0))
	if [ $# -lt 1 ]; then
		while [[ ! $CC =~ ^[A-Za-z]{2}$ || ($SRVTOT = 0) ]]; do
			echo -e -n "Enter a 2 Letter Country Abbreviation (e.g., gb, de, au):  "
			read -r CC
			lcc=`echo $CC | tr '[:upper:]' '[:lower:]'`
			curl -s https://public-dns.info/nameserver/$lcc.txt > ./dnssrv_list.txt
			IFS=$'\n' read -d '' -r -a DNSSRV < ./dnssrv_list.txt
			rm ./dnssrv_list.txt
			((SRVTOT=${#DNSSRV[@]}))
		done
	else
		CC=`echo $1`
                lcc=`echo $CC | tr '[:upper:]' '[:lower:]'`
                curl -s https://public-dns.info/nameserver/$lcc.txt > ./dnssrv_list.txt
                IFS=$'\n' read -d '' -r -a DNSSRV < ./dnssrv_list.txt
                rm ./dnssrv_list.txt
                ((SRVTOT=${#DNSSRV[@]}))
                while [[ ! $CC =~ ^[A-Za-z]{2}$ || ($SRVTOT = 0) ]]; do
                        echo -e -n "Enter a 2 Letter Country Abbreviation (e.g., gb, de, au):  "
                        read -r CC
                        lcc=`echo $CC | tr '[:upper:]' '[:lower:]'`
                        curl -s https://public-dns.info/nameserver/$lcc.txt > ./dnssrv_list.txt
                        IFS=$'\n' read -d '' -r -a DNSSRV < ./dnssrv_list.txt
                        rm ./dnssrv_list.txt
                        ((SRVTOT=${#DNSSRV[@]}))
		done
	fi
#
# How many servers are in the array?
echo -e "According to https://public-dns.info there are $SRVTOT DNS servers in $lcc at this time!\n"

if [ $SRVTOT -lt 20 ] ; then
	if [ $SRVTOT -eq 1 ] ; then
		echo -e "*** Now Testing ${DNSSRV[0]}, <Ctrl+c> to skip ***"
		echo
       		echo -e "dig @${DNSSRV[0]} NAPTR edge.uc.fuze.site +short +timeout=3\n"
       		dig @${DNSSRV[0]} NAPTR edge.uc.fuze.site +short +timeout=3
		exit 
	fi
#
# Found this method to print the array nicely into columns.  The "tab stop" in the printf notation helps.
	echo "Here's the whole list:"
	((b=1))
	for value in "${DNSSRV[@]}"; do 
    		printf "%-8s\n" "$b.  ${value}"
		((b=$b+1))
	done | column
else
	echo "Printing the first 20 from the list, but there are $SRVTOT DNS servers in $lcc:"
	((b=1))
	for k in {0..19}; do
    		printf "%-8s\n" "$b.  ${DNSSRV[$k]}"
		((b=$b+1))
	done | column
fi

echo 


# Ask how many to poll?
# set a temporary variable "snum" to be larger than the number of items in the DNSSRV array count SRVTOT
#
((snum=$SRVTOT+1))

#
# Now the while-do loop should continue until we get a value between 1 and the number of servers, and nothing else.
#
while [ $snum -gt $SRVTOT ]; do
	echo -e -n "How many of the $SRVTOT servers in $lcc should be tested (i.e., a number from [1-$SRVTOT], 0 to exit)?  " 
	read -r newnum
	if [ -z $newnum ] ; then 
		((snum=$SRVTOT+1))
	elif (( $newnum == 0 )) ; then
		exit 
	elif (( $newnum >= 1 && $newnum <= $SRVTOT )) ; then
                ((snum=$newnum))
	else 
		((snum=$SRVTOT+1))
	fi
done
#
# Since the array is "0 based" subract 1 from snum, and then make sure all the loops start with "0" too
#
((snum=$snum-1))
echo "Here is the list of DNS Servers to test:"
for i in $(seq 0 $snum)
	do
		((m=$i+1))
		echo -e "\t$m.  ${DNSSRV[$i]}"
	done
#
# Lookup the Fuze Domain from the DNS Server in that Country


((a=0))
for j in $(seq 0 $snum)
	do
		echo -e "*** Now Testing ${DNSSRV[$j]}, <Ctrl+c> to skip ***"
		if grep -q ":" <<< ${DNSSRV[$j]}; then
			echo -e "*** ${DNSSRV[$j]} Fail (Skipping IPv6 Result) ***\n"
			continue
		fi
		NAPTEST=`dig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3`
		if grep -q "timed" <<< $NAPTEST; then 
			echo -e "*** ${DNSSRV[$j]} Fail (Timeout) ***\n"
			continue
		elif [[ -z $NAPTEST ]]; then
			echo -e "*** ${DNSSRV[$j]} Fail (No Recursion) ***\n"
			continue
		fi
       		echo -e "\ndig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3"
		dig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3
       		ANSWER[$a]=`dig @${DNSSRV[$j]} NAPTR edge.uc.fuze.site +short +timeout=3 | head -1 | cut -d " " -f 6`
       		
		echo -e "\ndig @${DNSSRV[$j]} SRV ${ANSWER[$a]} +short +timeout=3"
	  	dig @${DNSSRV[$j]} SRV ${ANSWER[$a]} +short +timeout=3	
       		ANSWER[(($a+1))]=`dig @${DNSSRV[$j]} SRV ${ANSWER[$a]} +short +timeout=3 | head -1 | cut -d " " -f 4`

		ATEST=`dig @${DNSSRV[$j]} SRV ${ANSWER[$a]} +short +timeout=3`
		if grep -q "timed" <<< $ATEST; then
			echo -e "*** ${DNSSRV[$j]} Fail (SRV Timeout) ***\n"
			continue
		fi
		echo -e "\ndig @${DNSSRV[$j]} ${ANSWER[$a+1]} +short +timeout=3"
		dig @${DNSSRV[$j]} ${ANSWER[$a+1]} +short +timeout=3
       		ANSWER[(($a+2))]=`dig @${DNSSRV[$j]} ${ANSWER[(($a+1))]} +short +timeout=3`

	#	echo -e "NAPTR:  ${ANSWER[$a]}"
	#	echo -e "SRV:  ${ANSWER[$a+1]}"
	#	echo -e "A:  ${ANSWER[$a+2]}\n"
	echo
	done
